name: DeploymentWorkflow

# Trigger this workflow on pushes to the specified branch
on:
  push:
    branches:
      - master
      - ts

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: SSH Deploy
        # Use the 'appleboy/ssh-action' action for SSH deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }} # Your server's IP address
          username: ${{ secrets.USERNAME }} # Your server's username
          key: ${{ secrets.SSH_PRIVATE_KEY }} # Your server's SSH private key
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            nvm use 20
            git stash
            cd /var/www/html/dev/siteWeb1 # Specify the path to your app directory on the server
            git remote add origin2 https://github.com/amaurypichat/siteWeb1.git
            nvm use 20
            NODE_OPTIONS=--max_old_space_size=2000
            git pull origin ts
            npm install --legacy-peer-deps
            npm run build
